# Generated by Django 5.2.13 on 2026-04-18 05:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lesson_type', models.CharField(choices=[('umumy', 'Umumy'), ('amaly', 'Amaly'), ('tejribe', 'Tejribe'), ('sohbet', 'Sohbet')], default='umumy', max_length=20)),
            ],
            options={
                'verbose_name': 'Sorag',
                'verbose_name_plural': 'Soraglar',
                'ordering': ['lesson_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Mugallym',
                'verbose_name_plural': 'Mugallymlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='survey.teacher')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['name', 'teacher__full_name'],
                'unique_together': {('name', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('umumy', 'Umumy'), ('amaly', 'Amaly'), ('tejribe', 'Tejribe'), ('sohbet', 'Sohbet')], default='umumy', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='survey.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='survey.teacher')),
            ],
            options={
                'verbose_name': 'Soragnama sessiyasy',
                'verbose_name_plural': 'Soragnama sessiyalary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.feedbacksession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question')),
            ],
            options={
                'verbose_name': 'Jogap',
                'verbose_name_plural': 'Jogaplar',
                'ordering': ['session', 'question'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
